from __future__ import annotations

from typing import Callable

from app.application.conversion_quality_history import prepare_quality_record, replace_quality_issues


def record_anonymous_conversion_event(
    conn,
    *,
    execute: Callable,
    event_id: str,
    created_at: str,
    anonymous_fingerprint: str,
    filename: str,
    model: str,
    conversion_type: str,
    status: str,
    transactions_count: int | None,
    pages_count: int | None,
    scanned_likely: bool | None,
    ocr_used: bool,
    ocr_pages_processed: int,
    duration_ms: int,
    canonical_warning_transactions_count: int = 0,
    balance_consistency_failed: int = 0,
    error_code: str | None = None,
    error_stage: str | None = None,
    error_subcode: str | None = None,
    exception_class: str | None = None,
    layout_inference_name: str | None = None,
    layout_inference_confidence: float | None = None,
    selected_parser: str | None = None,
    parser_selection_reason: str | None = None,
    pdf_page_count: int | None = None,
    extracted_char_count: int | None = None,
    ocr_attempted: bool = False,
    ocr_engine: str | None = None,
    file_sha256: str | None = None,
    parser_confidence_band: str | None = None,
    parser_coverage_rate: float | None = None,
    warning_types: list[str] | None = None,
    failure_diagnostics: dict[str, object] | None = None,
    quality_issues: list[dict[str, object]] | None = None,
) -> None:
    assessment, reason_codes_json, warning_types_json, failure_diagnostics_json = prepare_quality_record(
        status=status,
        conversion_type=conversion_type,
        transactions_count=transactions_count,
        layout_name=layout_inference_name,
        layout_confidence=layout_inference_confidence,
        selected_parser=selected_parser,
        warning_count=canonical_warning_transactions_count,
        balance_failed=balance_consistency_failed,
        parser_confidence_band=parser_confidence_band,
        parser_coverage_rate=parser_coverage_rate,
        warning_types=warning_types,
        failure_diagnostics=failure_diagnostics,
    )
    execute(
        conn,
        """
        INSERT INTO anonymous_conversion_events (
          id,
          created_at,
          anonymous_fingerprint,
          filename,
          model,
          conversion_type,
          status,
          transactions_count,
          pages_count,
          scanned_likely,
          ocr_used,
          ocr_pages_processed,
          duration_ms,
          canonical_warning_transactions_count,
          balance_consistency_failed,
          error_code,
          error_stage,
          error_subcode,
          exception_class,
          layout_inference_name,
          layout_inference_confidence,
          selected_parser,
          parser_selection_reason,
          pdf_page_count,
          extracted_char_count,
          ocr_attempted,
          ocr_engine,
          file_sha256,
          quality_status,
          quality_score,
          quality_rule_version,
          quality_reason_codes_json,
          parser_confidence_band,
          parser_coverage_rate,
          warning_types_json,
          failure_diagnostics_json
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(id)
        DO UPDATE SET
          created_at=excluded.created_at,
          anonymous_fingerprint=excluded.anonymous_fingerprint,
          filename=excluded.filename,
          model=excluded.model,
          conversion_type=excluded.conversion_type,
          status=excluded.status,
          transactions_count=excluded.transactions_count,
          pages_count=excluded.pages_count,
          scanned_likely=excluded.scanned_likely,
          ocr_used=excluded.ocr_used,
          ocr_pages_processed=excluded.ocr_pages_processed,
          duration_ms=excluded.duration_ms,
          canonical_warning_transactions_count=excluded.canonical_warning_transactions_count,
          balance_consistency_failed=excluded.balance_consistency_failed,
          error_code=excluded.error_code,
          error_stage=excluded.error_stage,
          error_subcode=excluded.error_subcode,
          exception_class=excluded.exception_class,
          layout_inference_name=excluded.layout_inference_name,
          layout_inference_confidence=excluded.layout_inference_confidence,
          selected_parser=excluded.selected_parser,
          parser_selection_reason=excluded.parser_selection_reason,
          pdf_page_count=excluded.pdf_page_count,
          extracted_char_count=excluded.extracted_char_count,
          ocr_attempted=excluded.ocr_attempted,
          ocr_engine=excluded.ocr_engine,
          file_sha256=excluded.file_sha256,
          quality_status=excluded.quality_status,
          quality_score=excluded.quality_score,
          quality_rule_version=excluded.quality_rule_version,
          quality_reason_codes_json=excluded.quality_reason_codes_json,
          parser_confidence_band=excluded.parser_confidence_band,
          parser_coverage_rate=excluded.parser_coverage_rate,
          warning_types_json=excluded.warning_types_json,
          failure_diagnostics_json=excluded.failure_diagnostics_json
        """,
        (
            event_id,
            created_at,
            anonymous_fingerprint.strip() or "unknown",
            filename.strip() or "unknown.pdf",
            model.strip() or "Nao identificado",
            conversion_type.strip() or "pdf-ofx",
            status.strip() or "Sucesso",
            transactions_count,
            pages_count,
            scanned_likely,
            bool(ocr_used),
            max(0, int(ocr_pages_processed or 0)),
            max(0, int(duration_ms or 0)),
            max(0, int(canonical_warning_transactions_count or 0)),
            max(0, int(balance_consistency_failed or 0)),
            (error_code or "").strip() or None,
            (error_stage or "").strip() or None,
            (error_subcode or "").strip() or None,
            (exception_class or "").strip() or None,
            (layout_inference_name or "").strip() or None,
            float(layout_inference_confidence) if layout_inference_confidence is not None else None,
            (selected_parser or "").strip() or None,
            (parser_selection_reason or "").strip() or None,
            pdf_page_count,
            extracted_char_count,
            bool(ocr_attempted),
            (ocr_engine or "").strip() or None,
            (file_sha256 or "").strip() or None,
            assessment.status,
            assessment.score,
            assessment.rule_version,
            reason_codes_json,
            (parser_confidence_band or "").strip() or None,
            float(parser_coverage_rate) if parser_coverage_rate is not None else None,
            warning_types_json,
            failure_diagnostics_json,
        ),
    )
    replace_quality_issues(
        conn,
        execute=execute,
        conversion_id=event_id,
        identity_type="anonymous",
        created_at=created_at,
        quality_reason_codes=assessment.reason_codes,
        quality_issues=quality_issues,
        error_code=(error_code or "").strip() or None,
    )
