from app.routers import access_control_common

SESSION_ACCESS_COOKIE_NAME = access_control_common.SESSION_ACCESS_COOKIE_NAME
resolve_user_token_with_session = access_control_common.resolve_user_token_with_session
